library(datasets)
data <- read.csv(file="household_power_consumption.txt", sep=";", na.strings=c("?"), colClasses = c("character","character",rep("numeric",7)))
data[[2]] <- strptime(paste(data[[1]],data[[2]]), format='%d/%m/%Y %H:%M:%S')
data[[1]] <- as.Date(data[[1]], format='%d/%m/%Y')
filtered <- data[data$Date >= as.Date('2007-02-01') & data$Date <= as.Date('2007-02-02')  ,]
par(mfrow=c(2,2))
plot(filtered[[2]],filtered[[3]],ylab="Global Active Power (kilowatts)", xlab="", type = 'l')
plot(filtered[[2]],filtered[[5]],ylab="Voltage", xlab="", type = 'l')
plot(filtered[[2]],filtered[[7]],ylab="Energy sub mettering", xlab="", type = 'l')
lines(filtered[[2]],filtered[[8]],col="red")
lines(filtered[[2]],filtered[[9]],col="blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex = 0.6, lty = 1,lwd=1, bty = 'n', col = c('black','red','blue'))
plot(filtered[[2]],filtered[[4]],ylab="Global_reactive_power", xlab="", type = 'l')
dev.copy(png, file = "plot4.png",width=480,height=480)
dev.off()